name = "dopingFVM"
uuid = "5b45d986-dd89-4206-a4bd-6fec840c3928"
authors = ["Felipe A. Díaz <felipe.diazm@userena.cl>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
DocStringExtensions = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
