name = "dopingFVM"
uuid = "5b45d986-dd89-4206-a4bd-6fec840c3928"
authors = ["Felipe A. Díaz <felipe.diazm@userena.cl>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1"
DocStringExtensions = "0.8"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
